/**
 *  AUTHOR:-> YASH KULAT.
 */
/**
 * 	THIS PACKAGE CONTAINS THE ALL SERVICES OF PROJECT.
 */
package com.project_domato.services;

/*
 *	IN SPRING BOOT, A SERVICE IS A CLASS IN THE APPLICATION'S LAYERED ARCHITECTURE
 * 	THAT CONTAINS THE CORE BUSINESS LOGIC. IT ACTS AS AN INTERMEDIARY BETWEEN THE
 * 	CONTROLLER (PRESENTATION LAYER) AND THE REPOSITORY (DATA ACCESS LAYER),
 * 	ORCHESTRATING OPERATIONS AND ENFORCING BUSINESS RULES.
 */