/**
 * 	AUTHOR:-> YASH KULAT
 */
/**
 * THIS PACAKAGE CONTAINS THE CONTROLLER OF THE PROJECT;
 */
package com.project_domato.controller;

/*
 * 	A CONTROLLER IN SPRING BOOT IS A JAVA CLASS THAT HANDLES INCOMING HTTP
 * 	REQUESTS AND PREPARES A RESPONSE. CONTROLLERS ARE A CORE PART OF THE SPRING
 * 	MVC (MODEL-VIEW-CONTROLLER) ARCHITECTURE AND ARE USED TO MANAGE THE FLOW OF
 * 	WEB APPLICATION OR REST API INTERACTIONS.
 */