/**
 * 	AUTHOR:-> YASH KULAT.
 */
/**
 * 	THIS PACKAGE CONTAINS ALL THE ENTITIES OF THE PROJECT.
 */
package com.project_domato.Entities;

/*
 * 	AN ENTITY IS ANYTHING WITH A DISTINCT, SEPARATE EXISTENCE, WHETHER REAL OR
 * 	CONCEPTUAL, TANGIBLE OR ABSTRACT, LIKE A PERSON, ORGANIZATION, OBJECT, OR
 * 	EVEN AN IDEA, TREATED AS A SINGLE, IDENTIFIABLE UNIT IN VARIOUS CONTEXTS FROM
 * 	LAW AND BUSINESS TO COMPUTING.
 */