/**
 * 	AUTHOR:-> YASH KULAT;
 */
package com.project_domato.enums;

/**
 * 	THIS IS FOODCATEGORY ENUM HAS FOLLOWING CATEGORIES,
 * 	FOODCATE_SALAD,
	FOODCATE_ROLLS,
	FOODCATE_DESERTS,
	FOODCATE_SANDWITCH,
	FOODCATE_CAKE,
	FOODCATE_PUREVEG,
	FOODCATE_PASTA,
	FOODCATE_NOODLES
 */
public enum FoodCategory {
	FOODCATE_SALAD,
	FOODCATE_ROLLS,
	FOODCATE_DESERTS,
	FOODCATE_SANDWITCH,
	FOODCATE_CAKE,
	FOODCATE_PUREVEG,
	FOODCATE_PASTA,
	FOODCATE_NOODLES,
	FOODCATE_NOODLESWITH
}
