/**
 * 	AUTHOR:-> YASH KULAT
 */
/**
 * THIS PACAKAGE CONTAINS ALL ENUMS OF THE PROJECT
 */
package com.project_domato.enums;

/*
 * 	ENUMS (ENUMERATIONS) IN SPRING BOOT ARE A TYPE-SAFE AND MAINTAINABLE WAY TO
 * 	DEFINE A FIXED SET OF CONSTANTS, COMMONLY USED FOR REPRESENTING STATUSES,
 * 	ROLES, OR TYPES IN APPLICATIONS. THEY INTEGRATE SEAMLESSLY ACROSS DIFFERENT
 * 	LAYERS OF A SPRING BOOT APPLICATION, INCLUDING JPA ENTITIES, REST APIS, AND
 * 	BUSINESS LOGIC.
 */