/**
 *  AUTHOR:-> YASH KULAT
 */
/**
 * THIS PACKAGE CONTAIN THE DATA TRANSFER OBJ OF ALL THE ENTITIES.
 */
package com.project_domato.dtos;

/*
 * 	A DATA TRANSFER OBJECT (DTO) IS A SIMPLE OBJECT IN SPRING BOOT USED TO CARRY
 * 	DATA BETWEEN DIFFERENT LAYERS OF AN APPLICATION, SUCH AS BETWEEN THE CLIENT
 * 	(WEB APPLICATION, API CONSUMER) AND THE SERVER, OR BETWEEN THE CONTROLLER AND
 * 	THE SERVICE LAYERS.
 */