/**
 * 	AUTHOR:-> YASH KULAT
 */
/**
 * THIS PACKAGE CONTAINS THE IMPLEMENTATION OF THE ALL SERVICES OF PROJECT;
 */
package com.project_domato.serviceImpls;

/*
 * 	IN SPRING BOOT, A SERVICE IMPLEMENTATION (IMPL) IS A CLASS THAT CONTAINS THE
 * 	APPLICATION'S BUSINESS LOGIC AND IS TYPICALLY ANNOTATED WITH @SERVICE. THIS
 * 	CLASS IS A SPRING BEAN, ALLOWING IT TO BE AUTOMATICALLY DETECTED DURING
 * 	COMPONENT SCANNING AND MANAGED BY THE SPRING IOC (INVERSION OF CONTROL)
 * 	CONTAINER FOR DEPENDENCY INJECTION.
 */