/**
 * 	 AUTHOR:-> YASH KULAT
 */
/**
 * 	THIS PACKAGE CONTAINS THE REPOSITORIES OF THE ALL ENTITIES.
 */
package com.project_domato.repositories;

/*
 * 	IN SPRING BOOT, A REPOSITORY IS AN INTERFACE THAT ACTS AS THE DATA ACCESS
 * 	LAYER (DAO), SIMPLIFYING THE INTERACTION WITH A DATABASE BY PROVIDING
 * 	AUTOMATIC CRUD (CREATE, READ, UPDATE, DELETE) OPERATIONS AND CUSTOM QUERY
 * 	METHODS WITHOUT REQUIRING MANUAL SQL CODE. THIS FUNCTIONALITY IS PART OF THE
 * 	SPRING DATA JPA MODULE.
 */